#Pharmacokinetic (PK) Drug Delivery Simulator.

In [ ]:
import numpy as np
np.set_printoptions(suppress=True, precision=2)
#  Simulation Timeline (0 to 24 hours, sampling every 6 minutes)
time_hours = np.arange(0, 24, 0.1)


initial_dose_mg = float(input("Enter the initial administered dose in mg: "))
elimination_rate_k = 0.25

remaining_in_blood = initial_dose_mg * np.exp(-elimination_rate_k * time_hours)
accumulated_in_tissue = initial_dose_mg * (1 - np.exp(-elimination_rate_k * time_hours)) * 0.4 # Assuming 40% targets tissue

max_tissue_concentration = np.max(accumulated_in_tissue)
half_dose_time_idx = np.where(remaining_in_blood <= (initial_dose_mg / 2))[0][0]
half_life_hours = time_hours[half_dose_time_idx]

#  analytical findings
print("--- PHARMACOKINETIC MODEL SUMMARY ---")
print(f"Initial Administered Dose: {initial_dose_mg} mg")
print(f"Calculated Biological Half-Life: {half_life_hours:.1f} hours")
print(f"Peak Accumulation in Target Tissue: {max_tissue_concentration:.2f} mg")

clinical_report = np.column_stack((time_hours, remaining_in_blood, accumulated_in_tissue))
print("\nFirst 6 rows of final matrix data [Time, Blood_mg, Tissue_mg]:")
print(clinical_report[:6])

Enter the initial administered dose in mg: 500
--- PHARMACOKINETIC MODEL SUMMARY ---
Initial Administered Dose: 500.0 mg
Calculated Biological Half-Life: 2.8 hours
Peak Accumulation in Target Tissue: 199.49 mg

First 6 rows of final matrix data [Time, Blood_mg, Tissue_mg]:
[[  0.   500.     0.  ]
 [  0.1  487.65   4.94]
 [  0.2  475.61   9.75]
 [  0.3  463.87  14.45]
 [  0.4  452.42  19.03]
 [  0.5  441.25  23.5 ]]


#Inventory and Loss Calculator

In [ ]:
time = np.arange (1,31,1)
batch_size= int(input("Enter batch size:"))
deg_rate=0.85
v_price= int(input("enter vial price:"))
potency=  100-(deg_rate*time)
expiry_index = np.where(potency<=80) [0][0]
expiry= time[expiry_index]
vials_sold_day= int(input("enter vial sold per day:"))
total_sold= vials_sold_day*expiry
vials_left= batch_size - total_sold
if vials_left<0:
  vials_left=0
  total_loss=0
else:
  total_loss= (v_price*vials_left)
print(f"total loss:{total_loss}")
print(f"expiry date:{expiry}")
print(f"vials left:{vials_left}")

Enter batch size:100
enter vial price:2
enter vial sold per day:2
total loss:104
expiry date:24
vials left:52
